def Categories():
    return {
            "Psoriasis pictures Lichen Planus and related diseases": "Psoriasis",
            "Seborrheic Keratoses and other Benign Tumors": "Seborrheic Keratoses",
            "Tinea Ringworm Candidiasis and other Fungal Infections": "Tinea",
            "Acne and Rosacea Photos": "Acne",
            "Eczema Photos": "Eczema",
            "Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions": "Actinic Keratosis Basal Cell Carcinoma",
            "Warts Molluscum and other Viral Infections": "Warts Molluscum",
            "Nail Fungus and other Nail Disease": "Nail Fungus",
            "Systemic Disease": "Systemic Disease",
            "Light Diseases and Disorders of Pigmentation": "Light Diseases",
            "Atopic Dermatitis Photos": "Atopic Dermatitis",
            "Vascular Tumors": "Vascular Tumors",
            "Melanoma Skin Cancer Nevi and Moles": "Melanoma Skin Cancer Nevi",
            "Bullous Disease Photos": "Bullous Disease",
            "Scabies Lyme Disease and other Infestations and Bites": "Scabies Lyme Disease",
            "Lupus and other Connective Tissue diseases": "Lupus",
            "Vasculitis Photos": "Vasculitis",
            "Herpes HPV and other STDs Photos": "Herpes HPV",
            "Exanthems and Drug Eruptions": "Exanthems",
            "Cellulitis Impetigo and other Bacterial Infections": "Cellulitis Impetigo",
            "Poison Ivy Photos and other Contact Dermatitis": "Poison Ivy",
            "Hair Loss Photos Alopecia and other Hair Diseases": "Hair Loss",
            "Urticaria Hives": "Urticaria"
            }

def Classes():
    return ['Acne and Rosacea Photos',
            'Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions',
            'Atopic Dermatitis Photos', 'Bullous Disease Photos',
            'Cellulitis Impetigo and other Bacterial Infections',
            'Eczema Photos', 'Exanthems and Drug Eruptions',
            'Hair Loss Photos Alopecia and other Hair Diseases',
            'Herpes HPV and other STDs Photos',
            'Light Diseases and Disorders of Pigmentation',
            'Lupus and other Connective Tissue diseases',
            'Melanoma Skin Cancer Nevi and Moles',
            'Nail Fungus and other Nail Disease',
            'Poison Ivy Photos and other Contact Dermatitis',
            'Psoriasis pictures Lichen Planus and related diseases',
            'Scabies Lyme Disease and other Infestations and Bites',
            'Seborrheic Keratoses and other Benign Tumors', 'Systemic Disease',
            'Tinea Ringworm Candidiasis and other Fungal Infections',
            'Urticaria Hives', 'Vascular Tumors', 'Vasculitis Photos',
            'Warts Molluscum and other Viral Infections']